list_of_prompts = [
    "A futuristic cityscape with flying cars and neon lights",
    "A time-traveling detective solving a mystery in ancient Egypt",
    "An underwater civilization of sentient sea creatures",
    "A cybernetic cowboy in a Wild West-inspired space colony",
    "A steampunk circus with mechanical animals and acrobats",
    "A robot exploring the wonders of a virtual reality garden",
    "A magical forest inhabited by talking animals and enchanted plants",
    "A superhero attending a support group for retired heroes",
    "A space explorer encountering a friendly alien species",
    "A post-apocalyptic world where nature has reclaimed the cities",
    "A wizard's academy where students learn to cast spells with technology",
    "A giant robot playing a musical instrument in a jazz band",
    "A parallel universe where physics behaves differently",
    "A haunted house with ghostly holograms and interactive scares",
    "An intergalactic chef cooking dishes from different planets",
    "A virtual reality game where players can shape the environment",
    "A flying pirate ship navigating the skies of a gas giant",
    "A bioengineered pet that can communicate with its owner",
    "A sentient robot experiencing human emotions for the first time",
    "A time-traveling photographer capturing historical moments",
    "A floating island with gravity-defying architecture",
    "An ancient artifact with the power to manipulate dreams",
    "A secret society of artists creating masterpieces with advanced technology",
    "A race of shape-shifting aliens living among humans",
    "A space station hosting an intergalactic talent show",
    "A genetically modified plant that produces glowing fruit",
    "A talking cat with the ability to predict the future",
    "A futuristic sports competition with gravity-defying rules",
    "A mind-reading device that reveals people's deepest desires",
    "A parallel dimension where dinosaurs never went extinct",
    "A robot detective solving crimes in a cyberpunk city",
    "A flying carpet ride through a city of floating islands",
    "An AI therapist helping individuals overcome their fears",
    "A virtual reality museum showcasing lost civilizations",
    "A scientist discovering a new element with extraordinary properties",
    "A time-traveling musician composing a song for the ages",
    "A robot uprising that leads to a peaceful coexistence",
    "An alien zoo with creatures from different galaxies",
    "A space colony with a unique form of government",
    "A bioengineered superhero with plant-based powers",
    "A wizard battling a dragon in a futuristic arena",
    "A robot explorer documenting the biodiversity of an alien planet",
    "A holographic art installation that reacts to emotions",
    "An underground city powered by geothermal energy",
    "A parallel universe where everyone has a doppelganger",
    "A sentient spaceship with a quirky personality",
    "A genetic experiment gone wrong resulting in cute yet dangerous creatures",
    "A scientist discovering a portal to a realm of pure energy",
    "A futuristic fashion show featuring clothing with built-in technology",
    "A robot dance party with synchronized moves and colorful lights",
    "A virtual reality therapy session for overcoming phobias",
    "An ancient book with the power to rewrite reality",
    "A floating market in the clouds with flying merchants",
    "A robot gardener tending to plants on a space station",
    "A holographic storyteller recounting tales from different galaxies",
    "A time-traveling chef exploring the culinary traditions of the past",
    "A genetically enhanced athlete competing in a future Olympics",
    "A parallel universe where magic and technology coexist",
    "A robot comedian performing stand-up in a futuristic comedy club",
    "An underwater research station studying the mysteries of the deep sea",
    "A virtual reality journey through the human mind",
    "A superhero school training the next generation of heroes",
    "A city skyline transformed by interactive light displays",
    "A robot orchestra playing classical music with a modern twist",
    "An alien artifact with the power to heal or harm",
    "A futuristic spa offering rejuvenating treatments with advanced technology",
    "A holographic zoo with extinct animals brought back to life",
    "A time-traveling explorer encountering historical figures",
    "A sentient spaceship embarking on a quest across the galaxy",
    "An AI companion that learns and adapts to its user's preferences",
    "A virtual reality meditation experience in a serene natural environment",
    "A robot mechanic fixing a spaceship in the depths of outer space",
    "A parallel dimension where physics follows dream logic",
    "A genetically modified pet capable of creating beautiful art",
    "A holographic concert featuring musicians from different planets",
    "An ancient alien language deciphered by a linguist",
    "A futuristic transportation system with levitating vehicles",
    "A robot chef preparing a meal with ingredients from different planets",
    "A space explorer encountering a cosmic entity of immense power",
    "A bioengineered forest that produces oxygen for a polluted world",
    "A virtual reality game that simulates the experience of being a superhero",
    "A holographic art gallery showcasing works from across the universe",
    "A robot philosopher pondering the meaning of existence",
    "An alien communication device that allows humans to speak with extraterrestrial beings",
    "A time-traveling historian documenting key events in history",
    "A virtual reality dance competition with participants from different planets",
    "A parallel universe where technology is powered by magic",
    "A genetically modified animal with the ability to generate electricity",
    "A holographic classroom where students learn from historical figures",
    "An underwater city powered by geothermal vents",
    "A sentient robot assisting humans in everyday tasks",
    "A space colony with a zero-gravity amusement park",
    "A scientist discovering a new form of renewable energy",
    "A bioengineered creature designed to clean up environmental pollution",
    "A parallel dimension where animals have human-like intelligence",
    "A holographic theater experience that immerses the audience in a fantastical world",
    "A robot explorer uncovering the mysteries of an ancient civilization",
    "An AI artist creating paintings inspired by human emotions",
    "A futuristic courtroom where AI serves as judges and lawyers",
    "A virtual reality beach vacation in a simulated tropical paradise",
    "A parallel universe where the laws of physics are governed by art",
    "A robot chef participating in a cooking competition with chefs from different planets",
    "A bioengineered garden with plants that change color based on emotions",
    "A holographic chess game with pieces that come to life",
    "An alien language expert deciphering messages from extraterrestrial civilizations",
    "A time-traveling diplomat negotiating peace between warring factions",
    "A virtual reality experience that allows users to explore the surface of distant planets",
    "A parallel dimension where dreams become reality",
    "A genetically modified pet with the ability to communicate through telepathy",
    "A holographic fashion show featuring clothing inspired by different time periods",
    "A robot architect designing futuristic buildings with innovative materials",
    "An alien artifact with the power to alter the fabric of reality",
    "A futuristic library with books that come to life when opened",
    "A virtual reality game that simulates the experience of flying like a bird",
    "A parallel universe where mythical creatures coexist with humans",
    "A robot explorer documenting the flora and fauna of an alien jungle",
    "An AI therapist providing counseling to individuals with emotional challenges",
    "A holographic museum showcasing inventions that changed the course of history",
    "A time-traveling detective solving crimes in different historical eras",
    "A virtual reality concert with musicians performing from different galaxies",
    "A parallel dimension where advanced technology is powered by nature",
    "A genetically modified pet with the ability to create portals to other dimensions",
    "A holographic art installation that reacts to the emotions of the audience",
    "An alien historian studying human civilization throughout the ages",
    "A futuristic city with self-driving cars and vertical gardens",
    "A robot mechanic repairing a spaceship on a distant planet",
    "A holographic zoo featuring extinct animals resurrected through advanced technology",
    "A virtual reality experience that allows users to explore the mysteries of the universe",
    "A parallel universe where music has the power to shape reality",
    "A bioengineered organism that can thrive in extreme environmental conditions",
    "A holographic theater production that tells the story of humanity's journey to the stars",
    "An AI companion designed to provide emotional support to individuals",
    "A virtual reality simulation of a post-apocalyptic world with rebuilding efforts",
    "A parallel dimension where individuals can access their past and future selves",
    "A robot artist creating sculptures using advanced materials and techniques",
    "A genetically modified plant with the ability to produce medicinal compounds",
    "A holographic classroom where students learn from AI-powered educators",
    "A time-traveling scientist conducting experiments to alter historical events",
    "A virtual reality game that simulates the experience of exploring uncharted planets",
    "A parallel universe where animals have evolved human-like societies",
    "A bioengineered creature with the ability to generate renewable energy",
    "A holographic fashion designer creating clothing with shape-shifting capabilities",
    "An alien linguist deciphering the languages of newly discovered extraterrestrial civilizations",
    "A futuristic transportation system with levitating trains and magnetic highways",
    "A robot explorer documenting the geology of an alien planet",
    "A holographic museum showcasing the achievements of different civilizations",
    "An underwater research facility studying the communication of marine life",
    "A virtual reality experience that allows users to witness historical events firsthand",
    "A parallel dimension where technology is powered by the collective consciousness",
    "A genetically modified pet with the ability to detect and neutralize pollutants",
    "A holographic theater production that explores the concept of parallel universes",
    "A time-traveling archaeologist uncovering artifacts from different time periods",
    "A virtual reality game that simulates the experience of being a superhero in a futuristic city",
    "A parallel universe where emotions have tangible effects on the environment",
    "A robot artist creating paintings inspired by the beauty of the cosmos",
    "A genetically modified plant that can thrive in zero-gravity environments",
    "A holographic classroom where students learn about the history of space exploration",
    "An AI companion designed to assist individuals with memory loss",
    "A virtual reality simulation of a futuristic city with advanced technologies",
    "A bioengineered organism with the ability to break down and recycle plastic waste",
    "A holographic fashion show featuring clothing inspired by celestial bodies",
    "An alien botanist studying Earth's diverse plant life",
    "A futuristic library with books that transport readers to different worlds",
    "A robot chef preparing meals with ingredients from sustainable sources",
    "A virtual reality game that simulates the experience of exploring the deep sea",
    "A parallel universe where people communicate through art instead of language",
    "A genetically modified pet with the ability to detect and alert to natural disasters",
    "A holographic art installation that reflects the collective emotions of a community",
    "A time-traveling musician composing a song that transcends time and space",
    "An AI therapist providing counseling to extraterrestrial beings experiencing emotions",
    "A virtual reality experience that allows users to interact with mythical creatures",
    "A parallel dimension where individuals have the ability to manipulate probability",
    "A robot explorer documenting the cultural practices of an ancient alien civilization",
    "A holographic fashion designer creating clothing that adapts to environmental conditions",
    "A genetically modified plant with the ability to generate bio-luminescent light",
    "A futuristic transportation system powered by renewable energy from space",
    "A virtual reality game that simulates the experience of living in a utopian society",
    "A parallel universe where individuals have wings and can fly freely",
    "A bioengineered organism that can thrive in extreme temperatures and harsh climates",
    "A holographic classroom where students learn about the interconnectedness of all life",
    "An AI companion designed to assist in environmental conservation efforts",
    "A time-traveling historian documenting the evolution of art across different eras",
    "A virtual reality simulation of a sustainable city with eco-friendly architecture",
    "A parallel dimension where technology is powered by the energy of emotions",
    "A robot artist creating sculptures that represent the harmony of nature and technology",
    "A genetically modified pet with the ability to purify air and water",
    "A holographic museum showcasing the achievements of environmental conservation",
    "An underwater research facility studying the communication and cooperation of marine species",
    "A virtual reality experience that allows users to witness the wonders of the natural world",
    "A parallel universe where individuals can harness the power of bioluminescence",
    "A bioengineered organism with the ability to extract pollutants from the soil",
    "A holographic theater production that explores the impact of human actions on the planet",
    "A time-traveling scientist conducting experiments to reverse the effects of climate change",
    "A virtual reality game that simulates the experience of being a guardian of the environment",
    "A parallel dimension where plants and animals communicate with each other",
    "A robot gardener tending to a garden of genetically modified plants with healing properties",
    "A genetically modified pet with the ability to assist in disaster relief efforts",
    "A holographic fashion show featuring clothing made from sustainable and recyclable materials",
    "An alien ecologist studying Earth's ecosystems and biodiversity",
    "A futuristic library with books that provide solutions to environmental challenges",
]