list_of_prompts = [
    "A <cat-toy> spaceship",
    "Design your ideal <cat-toy> playground",
    "Create a scene of a <cat-toy> exploring a magical forest",
    "Invent a futuristic <cat-toy> with built-in holographic displays",
    "An underwater adventure with a submarine-shaped <cat-toy>",
    "A <cat-toy> fashion show on the runway",
    "A group of <cat-toy>s having a picnic in a sunny meadow",
    "A <cat-toy> tea party with other whimsical creatures",
    "A <cat-toy> superhero soaring through the city skyline",
    "A steampunk-inspired <cat-toy> with gears and cogs",
    "An image of a <cat-toy> with wings, ready for takeoff",
    "A <cat-toy> in a cozy library surrounded by miniature books",
    "A <cat-toy> in a retro diner enjoying a milkshake",
    "A zen garden scene with a meditating <cat-toy>",
    "A <cat-toy> as the captain of a pirate ship on the high seas",
    "An image of a <cat-toy> on a treasure hunt in a mystical cave",
    "A group of <cat-toy>s having a movie night with tiny popcorn",
    "A <cat-toy> as the king or queen of a majestic castle",
    "An image of a <cat-toy> leading a parade with other toys",
    "A carnival scene with a <cat-toy> on a carousel",
    "A <cat-toy> rock band performing on a miniature stage",
    "A snowy winter wonderland with <cat-toy> snowmen",
    "A beach vacation scene with <cat-toy>s building sandcastles",
    "An image of a <cat-toy> hosting a talk show with toy guests",
    "A retro diner with a jukebox and a dancing <cat-toy>",
    "A <cat-toy> traveling through time with a time machine",
    "A gardening scene with <cat-toy>s tending to tiny plants",
    "An image of a <cat-toy> chef cooking up a storm in a tiny kitchen",
    "A cityscape with skyscrapers and a <cat-toy> as a giant robot",
    "A <cat-toy> on a hot air balloon adventure in the clouds",
    "A scenic mountain landscape with <cat-toy>s hiking",
    "An image of a <cat-toy> at a masquerade ball in a dollhouse",
    "A jungle safari with <cat-toy>s exploring the wilderness",
    "A <cat-toy> art gallery with miniature paintings on display",
    "A beach party with <cat-toy>s enjoying the sun and surf",
    "A bustling city scene with <cat-toy>s riding in toy cars",
    "An image of a <cat-toy> as an archaeologist discovering toy artifacts",
    "A space exploration scene with <cat-toy>s in astronaut suits",
    "A cozy living room with <cat-toy>s gathered around a fireplace",
    "A <cat-toy> as a famous rock star performing on a stage",
    "An image of a <cat-toy> as a famous painter creating tiny masterpieces",
    "A medieval kingdom scene with <cat-toy>s in royal attire",
    "A movie set with <cat-toy>s starring in a blockbuster film",
    "A <cat-toy> in a fairytale castle surrounded by magic",
    "A futuristic cityscape with flying <cat-toy>s and hovercrafts",
    "An image of a <cat-toy> as an Olympic athlete competing in miniature sports",
    "A carnival with <cat-toy>s riding roller coasters and eating cotton candy",
    "A bustling market scene with <cat-toy>s shopping for miniature goods",
    "An image of a <cat-toy> in a detective office solving a toy mystery",
    "A beach volleyball game with <cat-toy>s enjoying the sand and sun",
    "A <cat-toy> as a scientist conducting experiments in a tiny lab",
    "A snowy ski resort with <cat-toy>s hitting the slopes",
    "An image of a <cat-toy> as a famous movie director filming a blockbuster",
    "A tropical island paradise with <cat-toy>s lounging on the beach",
    "A <cat-toy> as a famous explorer discovering new lands",
    "A circus tent with <cat-toy>s performing acrobatic tricks",
    "An image of a <cat-toy> as a renowned fashion designer showcasing a new collection",
    "A dinosaur-themed adventure with <cat-toy>s exploring a prehistoric world",
    "A <cat-toy> spa day with tiny massages and relaxation",
    "A bustling train station with <cat-toy>s waiting for their miniature trains",
    "An image of a <cat-toy> as a famous magician performing toy",
    "A futuristic <cat-toy> racing car",
    "An image of a <cat-toy> in a space-themed amusement park",
    "A steampunk <cat-toy> airship floating in the sky",
    "A <cat-toy> detective solving a mystery in a noir cityscape",
    "A group of <cat-toy>s forming a rock band in a garage",
    "A <cat-toy> train conducting a journey through a toy town",
    "An image of a <cat-toy> in a botanical garden filled with miniature plants",
    "A <cat-toy> as a famous explorer mapping out a toy continent",
    "A cyberpunk cityscape with <cat-toy>s as futuristic hackers",
    "A <cat-toy> as the captain of a toy submarine exploring the depths",
    "An image of a <cat-toy> as a DJ at a lively toy music festival",
    "A snowy scene with <cat-toy>s having a snowball fight",
    "A <cat-toy> as a famous chef preparing a gourmet meal in a tiny kitchen",
    "A retro arcade with <cat-toy>s playing classic video games",
    "An image of a <cat-toy> as a scientist conducting experiments with toy-sized equipment",
    "A <cat-toy> in a rainbow-colored toy wonderland",
    "A bustling toy city with <cat-toy>s as busy professionals",
    "A <cat-toy> as a superhero protecting a toy metropolis",
    "An image of a <cat-toy> in a serene zen garden",
    "A pirate ship crewed by adventurous <cat-toy>s searching for treasure",
    "A <cat-toy> in a library filled with miniature books",
    "A magical forest with <cat-toy>s encountering whimsical creatures",
    "An image of a <cat-toy> on a toy-sized roller coaster",
    "A toy zoo with <cat-toy>s as zookeepers caring for tiny animals",
    "A <cat-toy> as a famous painter creating masterpieces on tiny canvases",
    "A bustling toy market with <cat-toy>s shopping for miniature goods",
    "An image of a <cat-toy> as a famous movie director filming a blockbuster",
    "A <cat-toy> spa with relaxing treatments for toy relaxation",
    "A toy village with <cat-toy>s as inhabitants going about their day",
    "A <cat-toy> as a time traveler exploring different eras in toy history",
    "An image of a <cat-toy> in a toy-sized amusement park",
    "A desert oasis scene with <cat-toy>s enjoying the sand and sun",
    "A <cat-toy> in a toy-sized theater performing a play",
    "A toy train journey through scenic landscapes with <cat-toy> passengers",
    "An image of a <cat-toy> as a famous toy designer creating new creations",
    "A toy beach scene with <cat-toy>s building sandcastles",
    "A <cat-toy> as an astronaut exploring a miniature moon landscape",
    "A toy airport with <cat-toy>s as pilots and passengers",
    "An image of a <cat-toy> as a detective solving a toy mystery",
    "A mountain climbing adventure with <cat-toy>s conquering toy peaks",
    "A <cat-toy> in a toy-sized art studio creating miniature sculptures",
    "A bustling toy town with <cat-toy>s as residents going about their lives",
    "An image of a <cat-toy> as a famous magician performing toy illusions",
    "A toy beach party with <cat-toy>s enjoying the sun, sand, and surf",
    "A <cat-toy> as a mad scientist conducting experiments in a toy laboratory",
    "A toy ski resort with <cat-toy>s enjoying winter sports",
    "An image of a <cat-toy> as a famous toy model walking down a miniature runway",
    "A toy jungle safari with <cat-toy>s exploring the wilderness",
    "A <cat-toy> as a toy-sized superhero with unique powers",
    "A toy garden with <cat-toy>s tending to tiny plants",
    "An image of a <cat-toy> in a toy-sized movie theater watching a film",
    "A toy spaceship exploring the cosmos with <cat-toy> astronauts",
    "A <cat-toy> as a toy-sized explorer discovering hidden toy treasures",
    "A toy circus with <cat-toy>s performing acrobatic tricks",
    "An image of a <cat-toy> as a famous toy chef creating delicious miniature dishes",
    "A toy beach volleyball game with <cat-toy>s enjoying the sun and sand",
    "A <cat-toy> as a toy-sized scientist conducting experiments in a lab",
    "A toy ski lodge with <cat-toy>s relaxing by the fireplace after a day on the slopes",
    "An image of a <cat-toy> as a famous toy director filming a blockbuster",
    "A toy tropical island paradise with <cat-toy>s lounging on the beach",
    "A <cat-toy> as a toy-sized famous explorer discovering new toy lands",
    "A toy circus tent with <cat-toy>s performing daring acts",
    "An image of a <cat-toy> as a toy-sized famous fashion designer creating a new collection",
    "A dinosaur-themed adventure with <cat-toy>s exploring a toy prehistoric world",
    "A <cat-toy> spa day with relaxing treatments for toy relaxation",
    "A bustling toy train station with <cat-toy>s waiting for their miniature trains",
    "An image of a <cat-toy> as a toy-sized famous magician performing toy illusions",
    "A toy pirate ship crewed by adventurous <cat-toy>s searching for treasure",
    "A toy <cat-toy> spa day with tiny massages and relaxation",
    "A bustling toy train station with <cat-toy>s waiting for their miniature trains",
    "An image of a toy <cat-toy> as a famous magician performing toy illusions",
    "A toy village with <cat-toy>s as inhabitants going about their day",
    "A toy beach scene with <cat-toy>s building sandcastles",
    "A toy <cat-toy> as a famous toy model walking down a miniature runway",
    "A toy circus tent with <cat-toy>s performing daring acts",
    "A toy jungle safari with <cat-toy>s exploring the wilderness",
    "A toy <cat-toy> as a famous toy chef creating delicious miniature dishes",
    "A toy beach volleyball game with <cat-toy>s enjoying the sun and sand",
    "A toy tropical island paradise with <cat-toy>s lounging on the beach",
    "A toy <cat-toy> spa day with relaxing treatments for toy relaxation",
    "A toy dinosaur-themed adventure with <cat-toy>s exploring a toy prehistoric world",
    "A toy garden with <cat-toy>s tending to tiny plants",
    "A toy zoo with <cat-toy>s as zookeepers caring for tiny animals",
    "A toy market with <cat-toy>s shopping for miniature goods",
    "A toy village with <cat-toy>s as residents going about their lives",
    "A toy mountain climbing adventure with <cat-toy>s conquering toy peaks",
    "A toy train journey through scenic landscapes with <cat-toy> passengers",
    "A toy dinosaur-themed adventure with <cat-toy>s exploring a toy prehistoric world",
    "A toy market with <cat-toy>s shopping for miniature goods",
    "A toy zoo with <cat-toy>s as zookeepers caring for tiny animals",
    "A toy village with <cat-toy>s as residents going about their lives",
    "A toy beach scene with <cat-toy>s building sandcastles",
    "A toy jungle safari with <cat-toy>s exploring the wilderness",
    "A toy circus tent with <cat-toy>s performing daring acts",
    "A toy beach party with <cat-toy>s enjoying the sun, sand, and surf",
    "A toy ski resort with <cat-toy>s enjoying winter sports",
    "A toy garden with <cat-toy>s tending to tiny plants",
    "A toy ski lodge with <cat-toy>s relaxing by the fireplace after a day on the slopes",
    "A toy tropical island paradise with <cat-toy>s lounging on the beach",
    "A toy airport with <cat-toy>s as pilots and passengers",
    "A toy mountain climbing adventure with <cat-toy>s conquering toy peaks",
    "A toy dinosaur-themed adventure with <cat-toy>s exploring a toy prehistoric world",
    "A toy garden with <cat-toy>s tending to tiny plants",
    "A toy zoo with <cat-toy>s as zookeepers caring for tiny animals",
    "A toy market with <cat-toy>s shopping for miniature goods",
    "A toy village with <cat-toy>s as residents going about their lives",
    "A toy beach scene with <cat-toy>s building sandcastles",
    "A toy jungle safari with <cat-toy>s exploring the wilderness",
    "A toy circus tent with <cat-toy>s performing daring acts",
    "A toy beach party with <cat-toy>s enjoying the sun, sand, and surf",
    "A toy ski resort with <cat-toy>s enjoying winter sports",
    "A toy garden with <cat-toy>s tending to tiny plants",
    "A toy ski lodge with <cat-toy>s relaxing by the fireplace after a day on the slopes",
    "A toy tropical island paradise with <cat-toy>s lounging on the beach",
    "A toy airport with <cat-toy>s as pilots and passengers",
    "A toy mountain climbing adventure with <cat-toy>s conquering toy peaks",
    "A toy dinosaur-themed adventure with <cat-toy>s exploring a toy prehistoric world",
    "A toy garden with <cat-toy>s tending to tiny plants",
    "A toy zoo with <cat-toy>s as zookeepers caring for tiny animals",
    "A toy market with <cat-toy>s shopping for miniature goods",
    "A toy village with <cat-toy>s as residents going about their lives",
    "A toy beach scene with <cat-toy>s building sandcastles",
    "A toy jungle safari with <cat-toy>s exploring the wilderness",
    "A toy circus tent with <cat-toy>s performing daring acts",
    "A toy beach party with <cat-toy>s enjoying the sun, sand, and surf",
    "A toy ski resort with <cat-toy>s enjoying winter sports",
    "A toy garden with <cat-toy>s tending to tiny plants",
    "A toy ski lodge with <cat-toy>s relaxing by the fireplace after a day on the slopes",
    "A toy tropical island paradise with <cat-toy>s lounging on the beach",
    "A toy airport with <cat-toy>s as pilots and passengers",
    "A toy mountain climbing adventure with <cat-toy>s conquering toy peaks",
    "A toy dinosaur-themed adventure with <cat-toy>s exploring a toy prehistoric world",
    "A toy garden with <cat-toy>s tending to tiny plants",
    "A toy zoo with <cat-toy>s as zookeepers caring for tiny animals",
    "A toy market with <cat-toy>s shopping for miniature goods",
    "A toy village with <cat-toy>s as residents going about their lives",
    "A toy beach scene with <cat-toy>s building sandcastles",
    "A toy jungle safari with <cat-toy>s exploring the wilderness",
    "A toy circus tent with <cat-toy>s performing daring acts",
]